services:
  - type: web
    name: employee-management
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: employee-db
          property: connectionString

databases:
  - name: employee-db
    databaseName: employee_management
    user: admin